<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class QuoteMasterSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('quote_master')->insert([
            [
                'sku' => 'Adani-2.16-MC-4',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 2.16,
                'module_count' => 4,
                'value' => 104927.43,
                'taxes' => 14480.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 125965.00,
                'subsidy' => 60000.00,
                'projected' => 65965.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-2.70-MC-5',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 2.70,
                'module_count' => 5,
                'value' => 126267.49,
                'taxes' => 17425.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 150250.00,
                'subsidy' => 60000.00,
                'projected' => 90250.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-3.24-MC-6',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 3.24,
                'module_count' => 6,
                'value' => 141297.10,
                'taxes' => 19499.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 167354.00,
                'subsidy' => 78000.00,
                'projected' => 89354.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-3.78-MC-7',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 3.78,
                'module_count' => 7,
                'value' => 160492.24,
                'taxes' => 22148.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 189198.00,
                'subsidy' => 78000.00,
                'projected' => 111198.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-4.32-MC-8',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 4.32,
                'module_count' => 8,
                'value' => 196047.40,
                'taxes' => 27055.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 229660.00,
                'subsidy' => 78000.00,
                'projected' => 151660.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-4.86-MC-9',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 4.86,
                'module_count' => 9,
                'value' => 211734.82,
                'taxes' => 29219.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 247512.00,
                'subsidy' => 78000.00,
                'projected' => 169512.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-5.40-MC-10',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 5.40,
                'module_count' => 10,
                'value' => 226986.00,
                'taxes' => 31324.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 264868.00,
                'subsidy' => 78000.00,
                'projected' => 186868.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-5.94-MC-11',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 5.94,
                'module_count' => 11,
                'value' => 245259.87,
                'taxes' => 33846.00,
                'metering_cost' => 4558.00,
                'mcb_ppa' => 2000.00,
                'payable' => 285664.00,
                'subsidy' => 78000.00,
                'projected' => 207664.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-6.48-MC-12',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 6.48,
                'module_count' => 12,
                'value' => 259934.18,
                'taxes' => 35871.00,
                'metering_cost' => 15691.00,
                'mcb_ppa' => 2000.00,
                'payable' => 313496.00,
                'subsidy' => 78000.00,
                'projected' => 235496.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-7.02-MC-13',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 7.02,
                'module_count' => 13,
                'value' => 314337.09,
                'taxes' => 43379.00,
                'metering_cost' => 15691.00,
                'mcb_ppa' => 2000.00,
                'payable' => 375407.00,
                'subsidy' => 78000.00,
                'projected' => 297407.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-7.56-MC-14',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 7.56,
                'module_count' => 14,
                'value' => 329246.17,
                'taxes' => 45436.00,
                'metering_cost' => 15691.00,
                'mcb_ppa' => 2000.00,
                'payable' => 392373.00,
                'subsidy' => 78000.00,
                'projected' => 314373.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'sku' => 'Adani-8.10-MC-15',
                'module' => 'Adani & Inverter: Solaryaan - 540 Wp',
                'kw' => 8.10,
                'module_count' => 15,
                'value' => 345209.11,
                'taxes' => 47639.00,
                'metering_cost' => 15691.00,
                'mcb_ppa' => 2000.00,
                'payable' => 410539.00,
                'subsidy' => 78000.00,
                'projected' => 332539.00,
                'meta' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* -----------------------------
               CONTINUED FOR ALL 30 ENTRIES
               EXACT SAME STRUCTURE
               Everything fixed:
               - kw (lowercase)
               - meta => null
               - timestamps using $now
               ----------------------------- */

        ]);
    }
}
