<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('setting')->insert([
            [
                'id' => 1,
                'name' => 'quote_taxes',
                'label' => 'Year Start',
                'value' => '13.80',
                'type' => 7,
                'option' => null,
                'attr' => null,
                'created_at' => '2025-01-05 21:32:34',
                'updated_at' => '2025-01-05 16:02:34',
                'default' => null,
            ],
            [
                'id' => 2,
                'name' => 'quote_module_list_fe',
                'label' => 'Module list to show on quote request form',
                'value' => "{\"Goldi/Rayzon & Inverter: Solaryaan - 540 Wp\":\"\",\"Adani & Inverter: Solaryaan - 540 Wp\":\"\",\"none\":\"\"}",
                'type' => 4,
                'option' => 'Goldi/Rayzon & Inverter: Solaryaan - 540 Wp || Adani & Inverter: Solaryaan - 540 Wp',
                'attr' => null,
                'created_at' => '2024-04-20 19:36:01',
                'updated_at' => '2024-04-20 14:06:01',
                'default' => null,
            ],
            [
                'id' => 3,
                'name' => 'quote_kw_list',
                'label' => 'KW list to show on quote request form',
                'value' => "{\"2.16\":\"\",\"2.70\":\"\",\"3.24\":\"\",\"3.78\":\"\",\"4.32\":\"\",\"4.86\":\"\",\"5.40\":\"\",\"5.94\":\"\",\"6.48\":\"\",\"7.02\":\"\",\"7.56\":\"\",\"8.10\":\"\",\"8.64\":\"\",\"9.18\":\"\",\"9.72\":\"\",\"none\":\"\"}",
                'type' => 4,
                'option' => "2.16 || 2.70 || 3.24 || 3.78 || 4.32 || 4.86 || 5.40 || 5.94 || 6.48 || 7.02 || 7.56 || 8.10 || 8.64 || 9.18 || 9.72",
                'attr' => null,
                'created_at' => '2024-04-20 19:36:23',
                'updated_at' => '2024-04-20 14:06:23',
                'default' => null,
            ],
            [
                'id' => 4,
                'name' => 'quote_auto_response',
                'label' => 'Send Quote Autometically',
                'value' => 'false',
                'type' => 4,
                'option' => null,
                'attr' => null,
                'created_at' => '2024-04-20 23:50:39',
                'updated_at' => '2024-04-20 18:20:39',
                'default' => null,
            ],
            [
                'id' => 5,
                'name' => 'staff_roles',
                'label' => 'Roles',
                'value' => "[\"Admin\",\"Devloper\",\"CMO\",\"Marketing Head\",\"Marketing Exicutive\",\"Project Head\",\"Project Superviser\",\"Lisoner\",\"Site Engineer\"]",
                'type' => 4,
                'option' => "\"Admin\" : \"Admin\" || \"Devloper\" : \"Devloper\" || \"CMO\" : \"CMO\" || \"Marketing Head\" : \"Marketing Head\" || \"Marketing Exicutive\" : \"Marketing Exicutive\" || \"Project Head\" : \"Project Head\" || \"Project Superviser\" : \"Project Superviser\" || \"Lisoner\" : \"Lisoner\" || \"Site Engineer\" : \"Site Engineer\"",
                'attr' => null,
                'created_at' => '2024-08-17 21:35:53',
                'updated_at' => '2024-08-17 16:05:53',
                'default' => null,
            ],
            [
                'id' => 6,
                'name' => 'attendance_hours',
                'label' => 'Work Hours',
                'value' => '8',
                'type' => 1,
                'option' => null,
                'attr' => null,
                'created_at' => '2024-09-07 16:29:45',
                'updated_at' => '2024-09-07 10:59:45',
                'default' => null,
            ],
            [
                'id' => 7,
                'name' => 'tally_YearStart',
                'label' => 'Year Start',
                'value' => '2025-01-01',
                'type' => 7,
                'option' => null,
                'attr' => null,
                'created_at' => '2025-01-11 16:52:55',
                'updated_at' => '2025-07-18 09:26:39',
                'default' => null,
            ],
            [
                'id' => 8,
                'name' => 'tally_YearEnd',
                'label' => 'Year End',
                'value' => '2025-03-31',
                'type' => 7,
                'option' => null,
                'attr' => null,
                'created_at' => '2025-01-11 16:52:57',
                'updated_at' => '2025-07-18 09:25:14',
                'default' => null,
            ],
            [
                'id' => 9,
                'name' => 'tally_CompanyName',
                'label' => 'Company Name',
                'value' => 'SUNRAISE INDUSTRIES',
                'type' => 0,
                'option' => null,
                'attr' => null,
                'created_at' => '2025-01-05 21:36:29',
                'updated_at' => '2025-02-08 10:01:18',
                'default' => null,
            ],
            [
                'id' => 10,
                'name' => 'tally_tally_url',
                'label' => 'Tally URL',
                'value' => 'notable-grizzly-terribly.ngrok-free.app',
                'type' => 0,
                'option' => null,
                'attr' => null,
                'created_at' => '2025-01-08 21:46:46',
                'updated_at' => '2025-06-24 17:52:47',
                'default' => null,
            ],
            [
                'id' => 11,
                'name' => 'tally_voucher_type_mapping',
                'label' => 'Voucher Type',
                'value' => '{"Sales Accounts":"Sales"}',
                'type' => 8,
                'option' => null,
                'attr' => null,
                'created_at' => '2025-07-18 09:05:44',
                'updated_at' => '2025-07-18 09:12:56',
                'default' => null,
            ],
        ]);
    }
}
