<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quotation</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #1A1A1A;
        }
        .header {
            border-bottom: 2px solid #F28C28;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .brand {
            font-size: 20px;
            font-weight: bold;
            color: #1E4D8D;
        }
        .muted {
            color: #666;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        td, th {
            padding: 8px;
            border: 1px solid #E2E8F0;
        }
        th {
            background: #F4F7FB;
            text-align: left;
        }
        .total {
            font-size: 14px;
            font-weight: bold;
            color: #F28C28;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>

<body>

{{-- HEADER --}}
<div class="header">
    <div class="brand">Sunraise Solar Solutions</div>
    <div class="muted">
        Quotation No: {{ $data->quotation_no }}<br>
        Date: {{ $data->created_at->format('d M Y') }}
    </div>
</div>

{{-- CUSTOMER --}}
<h4>Customer Details</h4>
<table>
    <tr>
        <th>Name</th>
        <td>{{ optional($data->lead->customer)->name }}</td>
    </tr>
    <tr>
        <th>Mobile</th>
        <td>{{ optional($data->lead->customer)->mobile }}</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>{{ optional($data->lead->customer)->email }}</td>
    </tr>
</table>

{{-- SYSTEM DETAILS --}}
<h4>System Configuration</h4>
<table>
    <tr>
        <th>Module</th>
        <td>{{ optional($data->lead->quoteMaster)->module }}</td>
    </tr>
    <tr>
        <th>Capacity</th>
        <td>{{ optional($data->lead->quoteMaster)->kw }} kW</td>
    </tr>
    <tr>
        <th>Module Count</th>
        <td>{{ optional($data->lead->quoteMaster)->module_count }}</td>
    </tr>
</table>

{{-- PRICING --}}
<h4>Pricing Breakdown</h4>
<table>
    <tr>
        <th>Description</th>
        <th align="right">Amount (₹)</th>
    </tr>
    <tr>
        <td>Value</td>
        <td style="text-align: right">{{ number_format($data->lead->quoteMaster->value ?? 0,2) }}</td>
    </tr>
    <tr>
        <td>Taxes</td>
        <td style="text-align: right">{{ number_format($data->lead->quoteMaster->taxes ?? 0,2) }}</td>
    </tr>
    <tr>
        <td>MCB/PPA</td>
        <td style="text-align: right">{{ number_format($data->lead->quoteMaster->mcb_ppa ?? 0,2) }}</td>
    </tr>
    <tr>
        <td>Metering Cost</td>
        <td style="text-align: right">{{ number_format($data->lead->quoteMaster->metering_cost ?? 0,2) }}</td>
    </tr>
    <tr style="height: 2px;"></tr>
    <tr>
        <td>Payable</td>
        <td style="text-align: right">{{ number_format($data->lead->quoteMaster->payable ?? 0,2) }}</td>
    </tr>
    <tr>
        <td>Discount</td>
        <td style="text-align: right">{{ number_format($data->discount ?? 0,2) }}</td>
    </tr>
    <tr style="height: 2px;"></tr>
    <tr>
        <td>Final Price</td>
        <td style="text-align: right">{{ number_format($data->final_price ?? 0,2) }}</td>
    </tr>
    <tr>
        <td>Subsidy</td>
        <td style="text-align: right">{{ number_format($data->lead->quoteMaster->subsidy ?? 0,2) }}</td>
    </tr>
    <tr style="height: 2px;"></tr>
    <tr>
        <td>Projected</td>
        <td style="text-align: right">{{ (number_format($data->final_price - $data->lead->quoteMaster->subsidy ?? 0,2)) }}</td>
    </tr>
    <tr>
        <td class="total">Final Payable</td>
        <td align="right" class="total">
            {{ number_format($data->final_price) }}
        </td>
    </tr>
</table>

{{-- NOTES --}}
@if($data->lead->quoteRequest?->notes)
<h4>Notes</h4>
<p>{{ $data->lead->quoteRequest->notes }}</p>
@endif

{{-- FOOTER --}}
<div class="footer">
    This data is system generated by Sunraise CRM.<br>
    Prices are indicative and subject to site survey and final approval.
</div>

</body>
</html>
